apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    app: myapp
spec:
  type: clusterip
  selector:
    app: myapp
  ports:
  - port:
      targetport: 80
      protocol: TCP
